apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "tf-graphsage-dist"
spec:
  tfReplicaSpecs:
    PS:
      replicas: 2
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - python
            - graph_learn_launcher.py
            - dist_train.py
            image: registry.cn-zhangjiakou.aliyuncs.com/pai-image/graph-learn:v0.1-gpu
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources:
              limits:
                cpu: '1'
            workingDir: /workspace/graph-learn/examples/tf/graphsage/
            volumeMounts:
              - mountPath: /mnt/data/nfs
                name: graphlearn-path
          volumes:
            - name: graphlearn-path
              hostPath:
                path: /mnt/data/nfs
    Worker:
      replicas: 2
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - python
            - graph_learn_launcher.py
            - dist_train.py
            image: registry.cn-zhangjiakou.aliyuncs.com/pai-image/graph-learn:v0.1-gpu
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources:
              limits:
                nvidia.com/gpu: 1
            workingDir: /workspace/graph-learn/examples/tf/graphsage/
            volumeMounts:
              - mountPath: /mnt/data/nfs
                name: graphlearn-path
          volumes:
            - name: graphlearn-path
              hostPath:
                path: /mnt/data/nfs

